// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: price.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPrice = `-- name: CreatePrice :one
INSERT INTO
    prices (
        id,
        category,
        price_washing,
        price_ironing,
        price_dyeing,
        cost_washing,
        cost_ironing,
        cost_dyeing
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, category, price_washing, price_ironing, created_at, price_dyeing, cost_washing, cost_ironing, cost_dyeing
`

type CreatePriceParams struct {
	ID           uuid.UUID `json:"id"`
	Category     string    `json:"category"`
	PriceWashing string    `json:"price_washing"`
	PriceIroning string    `json:"price_ironing"`
	PriceDyeing  string    `json:"price_dyeing"`
	CostWashing  string    `json:"cost_washing"`
	CostIroning  string    `json:"cost_ironing"`
	CostDyeing   string    `json:"cost_dyeing"`
}

func (q *Queries) CreatePrice(ctx context.Context, arg CreatePriceParams) (Price, error) {
	row := q.db.QueryRowContext(ctx, createPrice,
		arg.ID,
		arg.Category,
		arg.PriceWashing,
		arg.PriceIroning,
		arg.PriceDyeing,
		arg.CostWashing,
		arg.CostIroning,
		arg.CostDyeing,
	)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.PriceWashing,
		&i.PriceIroning,
		&i.CreatedAt,
		&i.PriceDyeing,
		&i.CostWashing,
		&i.CostIroning,
		&i.CostDyeing,
	)
	return i, err
}

const deletePrice = `-- name: DeletePrice :exec
DELETE
FROM
    prices
WHERE id = $1
`

func (q *Queries) DeletePrice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePrice, id)
	return err
}

const getPrice = `-- name: GetPrice :one
SELECT
    id, category, price_washing, price_ironing, created_at, price_dyeing, cost_washing, cost_ironing, cost_dyeing
FROM
    prices
WHERE
    id = $1
LIMIT
    1
`

func (q *Queries) GetPrice(ctx context.Context, id uuid.UUID) (Price, error) {
	row := q.db.QueryRowContext(ctx, getPrice, id)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.PriceWashing,
		&i.PriceIroning,
		&i.CreatedAt,
		&i.PriceDyeing,
		&i.CostWashing,
		&i.CostIroning,
		&i.CostDyeing,
	)
	return i, err
}

const listPrices = `-- name: ListPrices :many
SELECT
    id, category, price_washing, price_ironing, created_at, price_dyeing, cost_washing, cost_ironing, cost_dyeing
FROM
    prices
ORDER BY
    category
ASC
LIMIT
    $2 OFFSET $1
`

type ListPricesParams struct {
	OffsetArg int32 `json:"offset_arg"`
	LimitArg  int32 `json:"limit_arg"`
}

func (q *Queries) ListPrices(ctx context.Context, arg ListPricesParams) ([]Price, error) {
	rows, err := q.db.QueryContext(ctx, listPrices, arg.OffsetArg, arg.LimitArg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.PriceWashing,
			&i.PriceIroning,
			&i.CreatedAt,
			&i.PriceDyeing,
			&i.CostWashing,
			&i.CostIroning,
			&i.CostDyeing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesAll = `-- name: ListPricesAll :many
SELECT
    id, category, price_washing, price_ironing, created_at, price_dyeing, cost_washing, cost_ironing, cost_dyeing
FROM
    prices
ORDER BY
    category
ASC
`

func (q *Queries) ListPricesAll(ctx context.Context) ([]Price, error) {
	rows, err := q.db.QueryContext(ctx, listPricesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.PriceWashing,
			&i.PriceIroning,
			&i.CreatedAt,
			&i.PriceDyeing,
			&i.CostWashing,
			&i.CostIroning,
			&i.CostDyeing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesByCategory = `-- name: ListPricesByCategory :many
SELECT
    id, category, price_washing, price_ironing, created_at, price_dyeing, cost_washing, cost_ironing, cost_dyeing
FROM
    prices
WHERE 
    category ~* $1
ORDER BY
    category
ASC
LIMIT
    $3 OFFSET $2
`

type ListPricesByCategoryParams struct {
	Category  string `json:"category"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

func (q *Queries) ListPricesByCategory(ctx context.Context, arg ListPricesByCategoryParams) ([]Price, error) {
	rows, err := q.db.QueryContext(ctx, listPricesByCategory, arg.Category, arg.OffsetArg, arg.LimitArg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.PriceWashing,
			&i.PriceIroning,
			&i.CreatedAt,
			&i.PriceDyeing,
			&i.CostWashing,
			&i.CostIroning,
			&i.CostDyeing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrice = `-- name: UpdatePrice :one
UPDATE
    prices
SET
    category = $1,
    price_washing = $2,
    price_ironing = $3,
    price_dyeing = $4,
    cost_washing = $5,
    cost_ironing = $6, 
    cost_dyeing = $7
WHERE
    id = $8
RETURNING id, category, price_washing, price_ironing, created_at, price_dyeing, cost_washing, cost_ironing, cost_dyeing
`

type UpdatePriceParams struct {
	Category     string    `json:"category"`
	PriceWashing string    `json:"price_washing"`
	PriceIroning string    `json:"price_ironing"`
	PriceDyeing  string    `json:"price_dyeing"`
	CostWashing  string    `json:"cost_washing"`
	CostIroning  string    `json:"cost_ironing"`
	CostDyeing   string    `json:"cost_dyeing"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePrice(ctx context.Context, arg UpdatePriceParams) (Price, error) {
	row := q.db.QueryRowContext(ctx, updatePrice,
		arg.Category,
		arg.PriceWashing,
		arg.PriceIroning,
		arg.PriceDyeing,
		arg.CostWashing,
		arg.CostIroning,
		arg.CostDyeing,
		arg.ID,
	)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.PriceWashing,
		&i.PriceIroning,
		&i.CreatedAt,
		&i.PriceDyeing,
		&i.CostWashing,
		&i.CostIroning,
		&i.CostDyeing,
	)
	return i, err
}
