// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "service": {
    "ClientService": {
      /**
       * CreateClient
       * @param {Client} arg1 - Go Type: service.Client
       * @returns {Promise<Client>}  - Go Type: service.Client
       */
      "CreateClient": (arg1) => {
        return window.go.service.ClientService.CreateClient(arg1);
      },
      /**
       * GetClients
       * @returns {Promise<Array<Client>>}  - Go Type: []service.Client
       */
      "GetClients": () => {
        return window.go.service.ClientService.GetClients();
      },
      /**
       * GetClientsByIdentification
       * @param {number} arg1 - Go Type: int32
       * @param {number} arg2 - Go Type: int32
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<Array<Client>>}  - Go Type: []service.Client
       */
      "GetClientsByIdentification": (arg1, arg2, arg3) => {
        return window.go.service.ClientService.GetClientsByIdentification(arg1, arg2, arg3);
      },
      /**
       * GetClientsByName
       * @param {number} arg1 - Go Type: int32
       * @param {number} arg2 - Go Type: int32
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<Array<Client>>}  - Go Type: []service.Client
       */
      "GetClientsByName": (arg1, arg2, arg3) => {
        return window.go.service.ClientService.GetClientsByName(arg1, arg2, arg3);
      },
      /**
       * GetClientsList
       * @param {number} arg1 - Go Type: int32
       * @param {number} arg2 - Go Type: int32
       * @returns {Promise<Array<Client>>}  - Go Type: []service.Client
       */
      "GetClientsList": (arg1, arg2) => {
        return window.go.service.ClientService.GetClientsList(arg1, arg2);
      },
      /**
       * UpdateClient
       * @param {Client} arg1 - Go Type: service.Client
       * @returns {Promise<Client>}  - Go Type: service.Client
       */
      "UpdateClient": (arg1) => {
        return window.go.service.ClientService.UpdateClient(arg1);
      },
    },
    "GarmentService": {
      /**
       * GetSumaryGarments
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<SumaryGarmentsResults>}  - Go Type: service.SumaryGarmentsResults
       */
      "GetSumaryGarments": (arg1, arg2) => {
        return window.go.service.GarmentService.GetSumaryGarments(arg1, arg2);
      },
    },
    "OrderService": {
      /**
       * CreateOrder
       * @param {Order} arg1 - Go Type: service.Order
       * @param {boolean} arg2 - Go Type: bool
       * @returns {Promise<Order>}  - Go Type: service.Order
       */
      "CreateOrder": (arg1, arg2) => {
        return window.go.service.OrderService.CreateOrder(arg1, arg2);
      },
      /**
       * GetCurrentOrderSequence
       * @returns {Promise<number>}  - Go Type: int32
       */
      "GetCurrentOrderSequence": () => {
        return window.go.service.OrderService.GetCurrentOrderSequence();
      },
      /**
       * GetNextOrderIdentifier
       * @returns {Promise<number>}  - Go Type: int32
       */
      "GetNextOrderIdentifier": () => {
        return window.go.service.OrderService.GetNextOrderIdentifier();
      },
      /**
       * GetOrderByClientName
       * @param {string} arg1 - Go Type: string
       * @param {number} arg2 - Go Type: int32
       * @param {number} arg3 - Go Type: int32
       * @returns {Promise<Array<Order>>}  - Go Type: []service.Order
       */
      "GetOrderByClientName": (arg1, arg2, arg3) => {
        return window.go.service.OrderService.GetOrderByClientName(arg1, arg2, arg3);
      },
      /**
       * GetOrderByIdentifier
       * @param {string} arg1 - Go Type: string
       * @param {number} arg2 - Go Type: int32
       * @param {number} arg3 - Go Type: int32
       * @returns {Promise<Array<Order>>}  - Go Type: []service.Order
       */
      "GetOrderByIdentifier": (arg1, arg2, arg3) => {
        return window.go.service.OrderService.GetOrderByIdentifier(arg1, arg2, arg3);
      },
      /**
       * GetOrdersList
       * @param {number} arg1 - Go Type: int32
       * @param {number} arg2 - Go Type: int32
       * @returns {Promise<Array<Order>>}  - Go Type: []service.Order
       */
      "GetOrdersList": (arg1, arg2) => {
        return window.go.service.OrderService.GetOrdersList(arg1, arg2);
      },
      /**
       * ListOrdersByRange
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {number} arg3 - Go Type: int32
       * @param {number} arg4 - Go Type: int32
       * @param {string} arg5 - Go Type: string
       * @returns {Promise<OrderPagination>}  - Go Type: service.OrderPagination
       */
      "ListOrdersByRange": (arg1, arg2, arg3, arg4, arg5) => {
        return window.go.service.OrderService.ListOrdersByRange(arg1, arg2, arg3, arg4, arg5);
      },
      /**
       * SetOrderDateAt
       * @param {UUID} arg1 - Go Type: uuid.UUID
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<Order>}  - Go Type: service.Order
       */
      "SetOrderDateAt": (arg1, arg2, arg3) => {
        return window.go.service.OrderService.SetOrderDateAt(arg1, arg2, arg3);
      },
    },
    "PriceService": {
      /**
       * CreatePrice
       * @param {Price} arg1 - Go Type: service.Price
       * @returns {Promise<Price>}  - Go Type: service.Price
       */
      "CreatePrice": (arg1) => {
        return window.go.service.PriceService.CreatePrice(arg1);
      },
      /**
       * DeletePrice
       * @param {UUID} arg1 - Go Type: uuid.UUID
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "DeletePrice": (arg1) => {
        return window.go.service.PriceService.DeletePrice(arg1);
      },
      /**
       * GetPrices
       * @returns {Promise<Array<Price>>}  - Go Type: []service.Price
       */
      "GetPrices": () => {
        return window.go.service.PriceService.GetPrices();
      },
      /**
       * GetPricesByCategory
       * @param {number} arg1 - Go Type: int32
       * @param {number} arg2 - Go Type: int32
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<Array<Price>>}  - Go Type: []service.Price
       */
      "GetPricesByCategory": (arg1, arg2, arg3) => {
        return window.go.service.PriceService.GetPricesByCategory(arg1, arg2, arg3);
      },
      /**
       * GetPricesList
       * @param {number} arg1 - Go Type: int32
       * @param {number} arg2 - Go Type: int32
       * @returns {Promise<Array<Price>>}  - Go Type: []service.Price
       */
      "GetPricesList": (arg1, arg2) => {
        return window.go.service.PriceService.GetPricesList(arg1, arg2);
      },
      /**
       * UpdatePrice
       * @param {Price} arg1 - Go Type: service.Price
       * @returns {Promise<Price>}  - Go Type: service.Price
       */
      "UpdatePrice": (arg1) => {
        return window.go.service.PriceService.UpdatePrice(arg1);
      },
    },
  },

};
export default go;
