// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * CreateOrder
       * @param {Order} arg1 - Go Type: main.Order
       * @returns {Promise<Order>}  - Go Type: main.Order
       */
      "CreateOrder": (arg1) => {
        return window.go.main.App.CreateOrder(arg1);
      },
      /**
       * GetNextOrderIdentifier
       * @returns {Promise<number>}  - Go Type: int32
       */
      "GetNextOrderIdentifier": () => {
        return window.go.main.App.GetNextOrderIdentifier();
      },
    },
  },

};
export default go;
